version: "3.7"

services:
  backend:
    build: backend
    ports:
      - "${BACKEND_HOST_PORT}5000"
      - "${DEBUGGER_HOST_PORT}10001"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${RUNSERVER:-gunicorn --reload --bind 0.0.0.0:5000 --timeout 480 backend.app:app}
    networks:
      - backend-network
    restart: ${DOCKER_RESTART:-no}

  proxy:
    build: proxy
    ports:
      - "${PROXY_HOST_PORT}80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    links:
      - backend:backend_api
    networks:
      - backend-network
      - nginx-gateway
    restart: ${DOCKER_RESTART:-no}

networks:
  backend-network:
  nginx-gateway:
      external:
          name: nginx-gateway
